<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use App\Models\Company\CompaniesCurrency;

class CompaniesCurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Truncate table before insert data
        CompaniesCurrency::truncate();
        $currency = [
            ["name" => "American Samoa", "flag" => "American_Samoa.png", "currency_name" => "USD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Andorra", "flag" => "Andorra.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Anguilla", "flag" => "Anguilla.png", "currency_name" => "XCD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Antarctica", "flag" => "Antarctica.png", "currency_name" => "GBP", "status" => "1", "currency_sign" => " £",],
            ["name" => "Antigua and Barbuda", "flag" => "Antigua_and_Barbuda.png", "currency_name" => "XCD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Argentina", "flag" => "Argentina.png", "currency_name" => "ARS", "status" => "1", "currency_sign" => "$",],
            ["name" => "Australia", "flag" => "Australia.png", "currency_name" => "AUD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Austria", "flag" => "Austria.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Bahamas", "flag" => "Bahamas.png", "currency_name" => "BSD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Barbados", "flag" => "Barbados.png", "currency_name" => "BBD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Belgium", "flag" => "Belgium.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Belize", "flag" => "Belize.png", "currency_name" => "BZD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Bermuda", "flag" => "Bermuda.png", "currency_name" => "BMD", "status" => "1", "currency_sign" => "$",],
            ["name" => "British Indian Ocean Territory", "flag" => "British_Indian_Ocean_Territory.png", "currency_name" => "USD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Brunei Darussalam", "flag" => "Brunei_Darussalam.png", "currency_name" => "BND", "status" => "1", "currency_sign" => "$",],
            ["name" => "Canada", "flag" => "Canada.png", "currency_name" => "CAD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Cape Verde", "flag" => "Cape_Verde.png", "currency_name" => "CVE", "status" => "1", "currency_sign" => "$",],
            ["name" => "Cayman Islands", "flag" => "Cayman_Islands.png", "currency_name" => "KYD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Chile", "flag" => "Chile.png", "currency_name" => "CLP", "status" => "1", "currency_sign" => "$",],
            ["name" => "China", "flag" => "China.png", "currency_name" => "CNY", "status" => "1", "currency_sign" => "¥",],
            ["name" => "Christmas Island", "flag" => "Christmas_Island.png", "currency_name" => "AUD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Cocos Islands", "flag" => "Cocos_Islands.png", "currency_name" => "AUD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Colombia", "flag" => "Colombia.png", "currency_name" => "COP", "status" => "1", "currency_sign" => "$",],
            ["name" => "Cook Islands", "flag" => "Cook_Islands.png", "currency_name" => "NZD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Cyprus", "flag" => "Cyprus.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Dominica", "flag" => "Dominica.png", "currency_name" => "DOP", "status" => "1", "currency_sign" => "$",],
            ["name" => "East Timor", "flag" => "East_Timor.png", "currency_name" => "USD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Ecuador", "flag" => "Ecuador.png", "currency_name" => "USD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Egypt", "flag" => "Egypt.png", "currency_name" => "EGP", "status" => "1", "currency_sign" => "£",],
            ["name" => "El Salvador", "flag" => "El_Salvador.png", "currency_name" => "SVC", "status" => "1", "currency_sign" => "$",],
            ["name" => "Estonia", "flag" => "Estonia.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Falkland Islands", "flag" => "Falkland_Islands.png", "currency_name" => "FKP", "status" => "1", "currency_sign" => "£",],
            ["name" => "Fiji", "flag" => "Fiji.png", "currency_name" => "FJD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Finland", "flag" => "Finland.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "France", "flag" => "France.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "French Guiana", "flag" => "French_Guiana.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "French Southern Territories", "flag" => "French_Southern_Territories.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Germany", "flag" => "Germany.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Ghana", "flag" => "Ghana.png", "currency_name" => "GHS", "status" => "1", "currency_sign" => "¢",],
            ["name" => "Gibraltar", "flag" => "Gibraltar.png", "currency_name" => "GIP", "status" => "1", "currency_sign" => "£",],
            ["name" => "Greece", "flag" => "Greece.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Grenada", "flag" => "Grenada.png", "currency_name" => "XCD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Guadeloupe", "flag" => "Guadeloupe.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Guam", "flag" => "Guam.png", "currency_name" => "USD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Guyana", "flag" => "Guyana.png", "currency_name" => "GYD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Heard and Mc Donald Islands", "flag" => "Heard_and_Mc_Donald_Islands.png", "currency_name" => "AUD ", "status" => "1", "currency_sign" => "$",],
            ["name" => "Holy See", "flag" => "Holy_See.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Hong Kong", "flag" => "Hong_Kong.png", "currency_name" => "HKD", "status" => "1", "currency_sign" => "$",],
            ["name" => "India", "flag" => "India.png", "currency_name" => "INR", "status" => "1", "currency_sign" => "Rs",],
            ["name" => "Indonesia", "flag" => "Indonesia.png", "currency_name" => "IDR", "status" => "1", "currency_sign" => "Rp",],
            ["name" => "Ireland", "flag" => "Ireland.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Italy", "flag" => "Italy.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Jamaica", "flag" => "Jamaica.png", "currency_name" => "JMD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Japan", "flag" => "Japan.png", "currency_name" => "JPY", "status" => "1", "currency_sign" => "¥",],
            ["name" => "Kiribati", "flag" => "Kiribati.png", "currency_name" => "AUD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Kuwait", "flag" => "Kuwait.png", "currency_name" => "KWD", "status" => "1", "currency_sign" => "KD",],
            ["name" => "Latvia", "flag" => "Latvia.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Lebanon", "flag" => "Lebanon.png", "currency_name" => "LBP", "status" => "1", "currency_sign" => "£",],
            ["name" => "Liberia", "flag" => "Liberia.png", "currency_name" => "LRD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Lithuania", "flag" => "Lithuania.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Luxembourg", "flag" => "Luxembourg.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Macau", "flag" => "Macau.png", "currency_name" => "MOP", "status" => "1", "currency_sign" => "$",],
            ["name" => "Malta", "flag" => "Malta.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Marshall Islands", "flag" => "Marshall_Islands.png", "currency_name" => "USD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Martinique", "flag" => "Martinique.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Mayotte", "flag" => "Mayotte.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Mexico", "flag" => "Mexico.png", "currency_name" => "MXN", "status" => "1", "currency_sign" => "$",],
            ["name" => "Micronesia", "flag" => "Micronesia.png", "currency_name" => "USD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Monaco", "flag" => "Monaco.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Montserrat", "flag" => "Montserrat.png", "currency_name" => "XCD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Namibia", "flag" => "Namibia.png", "currency_name" => "NAD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Nauru", "flag" => "Nauru.png", "currency_name" => "AUD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Nepal", "flag" => "Nepal.png", "currency_name" => "NPR", "status" => "1", "currency_sign" => "Rs",],
            ["name" => "Netherlands", "flag" => "Netherlands.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "New Zealand", "flag" => "New_Zealand.png", "currency_name" => "NZD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Nicaragua", "flag" => "Nicaragua.png", "currency_name" => "NIO", "status" => "1", "currency_sign" => "$",],
            ["name" => "Niue", "flag" => "Niue.png", "currency_name" => "NZD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Norfolk Island", "flag" => "Norfolk_Island.png", "currency_name" => "AUD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Northern Mariana Islands", "flag" => "Northern_Mariana_Islands.png", "currency_name" => "USD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Pakistan", "flag" => "Pakistan.png", "currency_name" => "PKR", "status" => "1", "currency_sign" => "Rs",],
            ["name" => "Palau", "flag" => "Palau.png", "currency_name" => "USD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Pitcairn", "flag" => "Pitcairn.png", "currency_name" => "NZD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Portugal", "flag" => "Portugal.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Puerto Rico", "flag" => "Puerto_Rico.png", "currency_name" => "USD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Reunion", "flag" => "Reunion.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Saint Kitts and Nevis", "flag" => "Saint_Kitts_and_Nevis.png", "currency_name" => "XCD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Saint Lucia", "flag" => "Saint_Lucia.png", "currency_name" => "XCD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Saint Vincent and the Grenadines", "flag" => "Saint_Vincent_and_the_Grenadines.png", "currency_name" => "XCD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Samoa", "flag" => "Samoa.png", "currency_name" => "WST", "status" => "1", "currency_sign" => "$",],
            ["name" => "San Marino", "flag" => "San_Marino.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Singapore", "flag" => "Singapore.png", "currency_name" => "SGD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Slovakia", "flag" => "Slovakia.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Slovenia", "flag" => "Slovenia.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Solomon Islands", "flag" => "Solomon_Islands.png", "currency_name" => "SBD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Somalia", "flag" => "Somalia.png", "currency_name" => "SOS", "status" => "1", "currency_sign" => "S",],
            ["name" => "South Africa", "flag" => "South_Africa.png", "currency_name" => "ZAR", "status" => "1", "currency_sign" => "R",],
            ["name" => "South Georgia", "flag" => "South_Georgia.png", "currency_name" => "GBP", "status" => "1", "currency_sign" => "£",],
            ["name" => "Spain", "flag" => "Spain.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Saint Helena", "flag" => "Saint_Helena.png", "currency_name" => "SHP", "status" => "1", "currency_sign" => "£",],
            ["name" => "Saint Pierre and Miquelon", "flag" => "Saint_Pierre_and_Miquelon.png", "currency_name" => "EURO", "status" => "1", "currency_sign" => "€",],
            ["name" => "Suriname", "flag" => "Suriname.png", "currency_name" => "SRD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Syrian Arab Republic", "flag" => "Syrian_Arab_Republic.png", "currency_name" => "SYP", "status" => "1", "currency_sign" => "£",],
            ["name" => "Taiwan", "flag" => "Taiwan.png", "currency_name" => "TWD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Tokelau", "flag" => "Tokelau.png", "currency_name" => "NZD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Tonga", "flag" => "Tonga.png", "currency_name" => "TOP", "status" => "1", "currency_sign" => "$",],
            ["name" => "Trinidad and Tobago", "flag" => "Trinidad_and_Tobago.png", "currency_name" => "TTD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Turks and Caicos Islands", "flag" => "Turks_and_Caicos_Islands.png", "currency_name" => "USD", "status" => "1", "currency_sign" => "$",],
            ["name" => "Tuvalu", "flag" => "Tuvalu.png", "currency_name" => "AUD", "status" => "1", "currency_sign" => "$",],
            ["name" => "United Kingdom", "flag" => "United_Kingdom.png", "currency_name" => "GBP", "status" => "2", "currency_sign" => "£",],
            ["name" => "United States", "flag" => "United_States.png", "currency_name" => "USD", "status" => "2", "currency_sign" => "$",],
            ["name" => "Uruguay", "flag" => "Uruguay.png", "currency_name" => "UYU", "status" => "1", "currency_sign" => "$",],
            ["name" => "Zimbabwe", "flag" => "Zimbabwe.png", "currency_name" => "ZWD", "status" => "1", "currency_sign" => "$",],
        ];

        CompaniesCurrency::insert($currency);
    }
}
