<?php

namespace Database\Seeders;

use App\Models\Company\CompaniesTimezone;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class CompaniesTimezoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Truncate table before insert data
        CompaniesTimezone::truncate();
        $now = Carbon::now();
        $industries = [["name"=>"Burkina Faso,BF","zone_value"=>"Africa/Abidjan","created_at"=> $now,],
        ["name"=>"Ghana ,GH","zone_value"=>"Africa/Accra","created_at"=> $now,],
        ["name"=>"Ethiopia ,ET","zone_value"=>"Africa/Addis_Ababa","created_at"=> $now,],
        ["name"=>"Algeria,DZ","zone_value"=>"Africa/Algiers","created_at"=> $now,],
        ["name"=>"Eritrea ,ER","zone_value"=>"Africa/Asmera","created_at"=> $now,],
        ["name"=>"Mali ,ML","zone_value"=>"Africa/Bamako","created_at"=> $now,],
        ["name"=>"Central African Republic,CF","zone_value"=>"Africa/Bangui","created_at"=> $now,],
        ["name"=>"Gambia,GM","zone_value"=>"Africa/Banjul","created_at"=> $now,],
        ["name"=>"Bissau,GW","zone_value"=>"Africa/Bissau","created_at"=> $now,],
        ["name"=>"Malawi ,MW","zone_value"=>"Africa/Blantyre","created_at"=> $now,],
        ["name"=>"Congo ,CG","zone_value"=>"Africa/Brazzaville","created_at"=> $now,],
        ["name"=>"Burundi ,BI","zone_value"=>"Africa/Bujumbura","created_at"=> $now,],
        ["name"=>"Egypt,EG","zone_value"=>"Africa/Cairo","created_at"=> $now,],
        ["name"=>"Morocco,MA","zone_value"=>"Africa/Casablanca","created_at"=> $now,],
        ["name"=>"Spain ,ES","zone_value"=>"Africa/Ceuta","created_at"=> $now,],
        ["name"=>"Guinea ,GN","zone_value"=>"Africa/Conakry","created_at"=> $now,],
        ["name"=>"Senegal ,SN","zone_value"=>"Africa/Dakar","created_at"=> $now,],
        ["name"=>"Tanzania ,TZ","zone_value"=>"Africa/Dar_es_Salaam","created_at"=> $now,],
        ["name"=>"Djibouti ,DJ","zone_value"=>"Africa/Djibouti","created_at"=> $now,],
        ["name"=>"Cameroon ,CM","zone_value"=>"Africa/Douala","created_at"=> $now,],
        ["name"=>"Laayoune","zone_value"=>"Africa/El_Aaiun","created_at"=> $now,],
        ["name"=>"Sierra Leone,SL","zone_value"=>"Africa/Freetown","created_at"=> $now,],
        ["name"=>"Botswana ,BW","zone_value"=>"Africa/Gaborone","created_at"=> $now,],
        ["name"=>"Zimbabwe ,ZW","zone_value"=>"Africa/Harare","created_at"=> $now,],
        ["name"=>"South Africa,ZA","zone_value"=>"Africa/Johannesburg","created_at"=> $now,],
        ["name"=>"South Sudan,SS","zone_value"=>"Africa/Juba","created_at"=> $now,],
        ["name"=>"Uganda ,UG","zone_value"=>"Africa/Kampala","created_at"=> $now,],
        ["name"=>"Sudan,SD","zone_value"=>"Africa/Khartoum","created_at"=> $now,],
        ["name"=>"Rwanda,RW","zone_value"=>"Africa/Kigali","created_at"=> $now,],
        ["name"=>"Kinshasa","zone_value"=>"Africa/Kinshasa","created_at"=> $now,],
        ["name"=>"Nigeria ,NG","zone_value"=>"Africa/Lagos","created_at"=> $now,],
        ["name"=>"Gabon ,GA","zone_value"=>"Africa/Libreville","created_at"=> $now,],
        ["name"=>"Togo ,TG","zone_value"=>"Africa/Lome","created_at"=> $now,],
        ["name"=>"Angola ,AO","zone_value"=>"Africa/Luanda","created_at"=> $now,],
        ["name"=>"Lubumbashi","zone_value"=>"Africa/Lubumbashi","created_at"=> $now,],
        ["name"=>"Zambia,ZM","zone_value"=>"Africa/Lusaka","created_at"=> $now,],
        ["name"=>"Equatorial Guinea,GQ","zone_value"=>"Africa/Malabo","created_at"=> $now,],
        ["name"=>"Mozambique ,MZ","zone_value"=>"Africa/Maputo","created_at"=> $now,],
        ["name"=>"Lesotho,LS","zone_value"=>"Africa/Maseru","created_at"=> $now,],
        ["name"=>"Eswatini ","zone_value"=>"Africa/Mbabane","created_at"=> $now,],
        ["name"=>"Somalia ,SO","zone_value"=>"Africa/Mogadishu","created_at"=> $now,],
        ["name"=>"Liberia,LR","zone_value"=>"Africa/Monrovia","created_at"=> $now,],
        ["name"=>"Kenya ,KE","zone_value"=>"Africa/Nairobi","created_at"=> $now,],
        ["name"=>"Chad ,TD","zone_value"=>"Africa/Ndjamena","created_at"=> $now,],
        ["name"=>"Niger ,NE","zone_value"=>"Africa/Niamey","created_at"=> $now,],
        ["name"=>"Mauritania ,MR","zone_value"=>"Africa/Nouakchott","created_at"=> $now,],
        ["name"=>"Burkina Faso,BF","zone_value"=>"Africa/Ouagadougou","created_at"=> $now,],
        ["name"=>"Benin,BG","zone_value"=>"Africa/Porto-Novo","created_at"=> $now,],
        ["name"=>"São Tomé & Príncipe,ST","zone_value"=>"Africa/Sao_Tome","created_at"=> $now,],
        ["name"=>"Timbuktu","zone_value"=>"Africa/Timbuktu","created_at"=> $now,],
        ["name"=>"Libya ,LY","zone_value"=>"Africa/Tripoli","created_at"=> $now,],
        ["name"=>"Tunisia ,TN","zone_value"=>"Africa/Tunis","created_at"=> $now,],
        ["name"=>"Namibia ,NA","zone_value"=>"Africa/Windhoek","created_at"=> $now,],
        ["name"=>"Adak","zone_value"=>"America/Adak","created_at"=> $now,],
        ["name"=>"Anchorage","zone_value"=>"America/Anchorage","created_at"=> $now,],
        ["name"=>"Anguilla ","zone_value"=>"America/Anguilla","created_at"=> $now,],
        ["name"=>"Antigua and Barbuda,AG","zone_value"=>"America/Antigua","created_at"=> $now,],
        ["name"=>"Brazil,BR","zone_value"=>"America/Araguaina","created_at"=> $now,],
        ["name"=>"Buenos Aires ,AR","zone_value"=>"America/Argentina/Buenos_Aires","created_at"=> $now,],
        ["name"=>"Catamarca Province","zone_value"=>"America/Argentina/Catamarca","created_at"=> $now,],
        ["name"=>"Comodoro Rivadavia","zone_value"=>"America/Argentina/ComodRivadavia","created_at"=> $now,],
        ["name"=>"Cordoba","zone_value"=>"America/Argentina/Cordoba","created_at"=> $now,],
        ["name"=>"Jujuy","zone_value"=>"America/Argentina/Jujuy","created_at"=> $now,],
        ["name"=>"La Rioja Province","zone_value"=>"America/Argentina/La_Rioja","created_at"=> $now,],
        ["name"=>"Mendoza","zone_value"=>"America/Argentina/Mendoza","created_at"=> $now,],
        ["name"=>"Rio Gallegos","zone_value"=>"America/Argentina/Rio_Gallegos","created_at"=> $now,],
        ["name"=>"Salta","zone_value"=>"America/Argentina/Salta","created_at"=> $now,],
        ["name"=>"San Juan","zone_value"=>"America/Argentina/San_Juan","created_at"=> $now,],
        ["name"=>"San Luis ","zone_value"=>"America/Argentina/San_Luis","created_at"=> $now,],
        ["name"=>"Tucumán","zone_value"=>"America/Argentina/Tucuman","created_at"=> $now,],
        ["name"=>"Ushuaia","zone_value"=>"America/Argentina/Ushuaia","created_at"=> $now,],
        ["name"=>"Aruba ","zone_value"=>"America/Aruba","created_at"=> $now,],
        ["name"=>"Asunción","zone_value"=>"America/Asuncion","created_at"=> $now,],
        ["name"=>"Atikokan","zone_value"=>"America/Atikokan","created_at"=> $now,],
        ["name"=>"Atka","zone_value"=>"America/Atka","created_at"=> $now,],
        ["name"=>"Bahia","zone_value"=>"America/Bahia","created_at"=> $now,],
        ["name"=>"Bahía de Banderas","zone_value"=>"America/Bahia_Banderas","created_at"=> $now,],
        ["name"=>"Barbados,BB","zone_value"=>"America/Barbados","created_at"=> $now,],
        ["name"=>"Belém","zone_value"=>"America/Belem","created_at"=> $now,],
        ["name"=>"Belize ,BZ","zone_value"=>"America/Belize","created_at"=> $now,],
        ["name"=>"Blanc-Sablon","zone_value"=>"America/Blanc-Sablon","created_at"=> $now,],
        ["name"=>" Boa Vista","zone_value"=>"America/Boa_Vista","created_at"=> $now,],
        ["name"=>"Colombia,CO","zone_value"=>"America/Bogota","created_at"=> $now,],
        ["name"=>"Boise","zone_value"=>"America/Boise","created_at"=> $now,],
        ["name"=>"Buenos Aires","zone_value"=>"America/Buenos_Aires","created_at"=> $now,],
        ["name"=>"Cambridge Bay","zone_value"=>"America/Cambridge_Bay","created_at"=> $now,],
        ["name"=>"Campo Grande","zone_value"=>"America/Campo_Grande","created_at"=> $now,],
        ["name"=>"Mexico,MX","zone_value"=>"America/Cancun","created_at"=> $now,],
        ["name"=>"Venezuela,VE","zone_value"=>"America/Caracas","created_at"=> $now,],
        ["name"=>"Catamarca ","zone_value"=>"America/Catamarca","created_at"=> $now,],
        ["name"=>"French Guiana,GF","zone_value"=>"America/Cayenne","created_at"=> $now,],
        ["name"=>"Cayman Islands,KY","zone_value"=>"America/Cayman","created_at"=> $now,],
        ["name"=>"Chicago,US","zone_value"=>"America/Chicago","created_at"=> $now,],
        ["name"=>"Chihuahua","zone_value"=>"America/Chihuahua","created_at"=> $now,],
        ["name"=>"Coral Harbour","zone_value"=>"America/Coral_Harbour","created_at"=> $now,],
        ["name"=>"Cordoba","zone_value"=>"America/Cordoba","created_at"=> $now,],
        ["name"=>"Costa Rica,CR","zone_value"=>"America/Costa_Rica","created_at"=> $now,],
        ["name"=>"Creston","zone_value"=>"America/Creston","created_at"=> $now,],
        ["name"=>"Cuiabá ,BR","zone_value"=>"America/Cuiaba","created_at"=> $now,],
        ["name"=>"Curaçao ,CW","zone_value"=>"America/Curacao","created_at"=> $now,],
        ["name"=>"Danmarkshavn ,GL","zone_value"=>"America/Danmarkshavn","created_at"=> $now,],
        ["name"=>"Dawson ,CA","zone_value"=>"America/Dawson","created_at"=> $now,],
        ["name"=>"Dawson Creek,CA","zone_value"=>"America/Dawson_Creek","created_at"=> $now,],
        ["name"=>"Denver,US","zone_value"=>"America/Denver","created_at"=> $now,],
        ["name"=>"Detroit","zone_value"=>"America/Detroit","created_at"=> $now,],
        ["name"=>"Dominica ,DM","zone_value"=>"America/Dominica","created_at"=> $now,],
        ["name"=>"Edmonton,CA","zone_value"=>"America/Edmonton","created_at"=> $now,],
        ["name"=>"Eirunepé ","zone_value"=>"America/Eirunepe","created_at"=> $now,],
        ["name"=>"El Salvador,SV","zone_value"=>"America/El_Salvador","created_at"=> $now,],
        ["name"=>"Ensenada","zone_value"=>"America/Ensenada","created_at"=> $now,],
        ["name"=>"Fortaleza ,BR","zone_value"=>"America/Fortaleza","created_at"=> $now,],
        ["name"=>"Fort Nelson,CA","zone_value"=>"America/Fort_Nelson","created_at"=> $now,],
        ["name"=>" Fort Wayne","zone_value"=>"America/Fort_Wayne","created_at"=> $now,],
        ["name"=>"Glace Bay,CA","zone_value"=>"America/Glace_Bay","created_at"=> $now,],
        ["name"=>"Godthab ,GL","zone_value"=>"America/Godthab","created_at"=> $now,],
        ["name"=>"Goose Bay","zone_value"=>"America/Goose_Bay","created_at"=> $now,],
        ["name"=>"Grand Turk","zone_value"=>"America/Grand_Turk","created_at"=> $now,],
        ["name"=>"Grenada ,GD","zone_value"=>"America/Grenada","created_at"=> $now,],
        ["name"=>"Guadeloupe ,GP","zone_value"=>"America/Guadeloupe","created_at"=> $now,],
        ["name"=>"Guatemala ,GT","zone_value"=>"America/Guatemala","created_at"=> $now,],
        ["name"=>"Ecuador,EC","zone_value"=>"America/Guayaquil","created_at"=> $now,],
        ["name"=>"Guyana ,GY","zone_value"=>"America/Guyana","created_at"=> $now,],
        ["name"=>"Halifax,CA","zone_value"=>"America/Halifax","created_at"=> $now,],
        ["name"=>"Cuba,CU","zone_value"=>"America/Havana","created_at"=> $now,],
        ["name"=>"Hermosillo,MX","zone_value"=>"America/Hermosillo","created_at"=> $now,],
        ["name"=>"Indianapolis","zone_value"=>"America/Indiana/Indianapolis","created_at"=> $now,],
        ["name"=>"Knox","zone_value"=>"America/Indiana/Knox","created_at"=> $now,],
        ["name"=>"Marengo,USA","zone_value"=>"America/Indiana/Marengo","created_at"=> $now,],
        ["name"=>"Petersburg,USA","zone_value"=>"America/Indiana/Petersburg","created_at"=> $now,],
        ["name"=>"Tell ,USA","zone_value"=>"America/Indiana/Tell_City","created_at"=> $now,],
        ["name"=>"Vevay,USA","zone_value"=>"America/Indiana/Vevay","created_at"=> $now,],
        ["name"=>"Vincennes,USA","zone_value"=>"America/Indiana/Vincennes","created_at"=> $now,],
        ["name"=>"Winamac,USA","zone_value"=>"America/Indiana/Winamac","created_at"=> $now,],
        ["name"=>"Indianapolis,USA","zone_value"=>"America/Indianapolis","created_at"=> $now,],
        ["name"=>"Inuvik,CA","zone_value"=>"America/Inuvik","created_at"=> $now,],
        ["name"=>"Iqaluit,CA","zone_value"=>"America/Iqaluit","created_at"=> $now,],
        ["name"=>"Jamaica ,JM","zone_value"=>"America/Jamaica","created_at"=> $now,],
        ["name"=>"Jujuy","zone_value"=>"America/Jujuy","created_at"=> $now,],
        ["name"=>"Juneau,USA","zone_value"=>"America/Juneau","created_at"=> $now,],
        ["name"=>"Louisville,USA","zone_value"=>"America/Kentucky/Louisville","created_at"=> $now,],
        ["name"=>"Monticello","zone_value"=>"America/Kentucky/Monticello","created_at"=> $now,],
        ["name"=>"Knox,USA","zone_value"=>"America/Knox_IN","created_at"=> $now,],
        ["name"=>"Kralendijk","zone_value"=>"America/Kralendijk","created_at"=> $now,],
        ["name"=>"Bolivia,BQ","zone_value"=>"America/La_Paz","created_at"=> $now,],
        ["name"=>"Lima,PE","zone_value"=>"America/Lima","created_at"=> $now,],
        ["name"=>"Los Angeles,USA","zone_value"=>"America/Los_Angeles","created_at"=> $now,],
        ["name"=>"Louisville,USA","zone_value"=>"America/Louisville","created_at"=> $now,],
        ["name"=>" Sint Maarten,SX","zone_value"=>"America/Lower_Princes","created_at"=> $now,],
        ["name"=>"Maceió,BR","zone_value"=>"America/Maceio","created_at"=> $now,],
        ["name"=>"Nicaragua,NI","zone_value"=>"America/Managua","created_at"=> $now,],
        ["name"=>"Manaus,BR","zone_value"=>"America/Manaus","created_at"=> $now,],
        ["name"=>"Marigot ","zone_value"=>"America/Marigot","created_at"=> $now,],
        ["name"=>"Martinique ,MQ","zone_value"=>"America/Martinique","created_at"=> $now,],
        ["name"=>"Matamoros","zone_value"=>"America/Matamoros","created_at"=> $now,],
        ["name"=>"Mazatlán,MX","zone_value"=>"America/Mazatlan","created_at"=> $now,],
        ["name"=>"Mendoza ","zone_value"=>"America/Mendoza","created_at"=> $now,],
        ["name"=>"Menominee,USA","zone_value"=>"America/Menominee","created_at"=> $now,],
        ["name"=>"Mérida","zone_value"=>"America/Merida","created_at"=> $now,],
        ["name"=>"Metlakatla,USA","zone_value"=>"America/Metlakatla","created_at"=> $now,],
        ["name"=>"Mexico City","zone_value"=>"America/Mexico_City","created_at"=> $now,],
        ["name"=>"Miquelon ,PM","zone_value"=>"America/Miquelon","created_at"=> $now,],
        ["name"=>"Moncton,CA","zone_value"=>"America/Moncton","created_at"=> $now,],
        ["name"=>"Monterrey ","zone_value"=>"America/Monterrey","created_at"=> $now,],
        ["name"=>"Uruguay,UY","zone_value"=>"America/Montevideo","created_at"=> $now,],
        ["name"=>"Montreal,CA","zone_value"=>"America/Montreal","created_at"=> $now,],
        ["name"=>"Montserrat ,MS","zone_value"=>"America/Montserrat","created_at"=> $now,],
        ["name"=>"Bahamas,BS","zone_value"=>"America/Nassau","created_at"=> $now,],
        ["name"=>"New York,USA","zone_value"=>"America/New_York","created_at"=> $now,],
        ["name"=>"Nipigon,CA","zone_value"=>"America/Nipigon","created_at"=> $now,],
        ["name"=>"Nome,USA","zone_value"=>"America/Nome","created_at"=> $now,],
        ["name"=>"Noronha ,BR","zone_value"=>"America/Noronha","created_at"=> $now,],
        ["name"=>"Beulah,USA","zone_value"=>"America/North_Dakota/Beulah","created_at"=> $now,],
        ["name"=>"Center,USA","zone_value"=>"America/North_Dakota/Center","created_at"=> $now,],
        ["name"=>"New Salem,USA","zone_value"=>"America/North_Dakota/New_Salem","created_at"=> $now,],
        ["name"=>"Nuuk,GL","zone_value"=>"America/Nuuk","created_at"=> $now,],
        ["name"=>"Ojinaga","zone_value"=>"America/Ojinaga","created_at"=> $now,],
        ["name"=>"Panama ,KY","zone_value"=>"America/Panama","created_at"=> $now,],
        ["name"=>"Pangnirtung","zone_value"=>"America/Pangnirtung","created_at"=> $now,],
        ["name"=>"Suriname,SR","zone_value"=>"America/Paramaribo","created_at"=> $now,],
        ["name"=>"Phoenix,USA","zone_value"=>"America/Phoenix","created_at"=> $now,],
        ["name"=>"Haiti ,HT","zone_value"=>"America/Port-au-Prince","created_at"=> $now,],
        ["name"=>"Puerto Rico,PR","zone_value"=>"America/Porto_Acre","created_at"=> $now,],
        ["name"=>"Porto Velho,BR","zone_value"=>"America/Porto_Velho","created_at"=> $now,],
        ["name"=>"Trinidad and Tobago,TT","zone_value"=>"America/Port_of_Spain","created_at"=> $now,],
        ["name"=>"Puerto Rico,PR","zone_value"=>"America/Puerto_Rico","created_at"=> $now,],
        ["name"=>"Punta Arenas","zone_value"=>"America/Punta_Arenas","created_at"=> $now,],
        ["name"=>"Rainy Rive,CA","zone_value"=>"America/Rainy_River","created_at"=> $now,],
        ["name"=>"Rankin Inlet,CA","zone_value"=>"America/Rankin_Inlet","created_at"=> $now,],
        ["name"=>"Recife,BR","zone_value"=>"America/Recife","created_at"=> $now,],
        ["name"=>"Regina,CA","zone_value"=>"America/Regina","created_at"=> $now,],
        ["name"=>"Resolute,CA","zone_value"=>"America/Resolute","created_at"=> $now,],
        ["name"=>"Rio Branco,BR","zone_value"=>"America/Rio_Branco","created_at"=> $now,],
        ["name"=>"Rosario","zone_value"=>"America/Rosario","created_at"=> $now,],
        ["name"=>"Santarém,BR","zone_value"=>"America/Santarem","created_at"=> $now,],
        ["name"=>" Santa Isabel","zone_value"=>"America/Santa_Isabel","created_at"=> $now,],
        ["name"=>" Santa Isabel","zone_value"=>"America/Santiago","created_at"=> $now,],
        ["name"=>"Dominican Republic,DO","zone_value"=>"America/Santo_Domingo","created_at"=> $now,],
        ["name"=>"São Paulo","zone_value"=>"America/Sao_Paulo","created_at"=> $now,],
        ["name"=>"Ittoqqortoormiit,GR","zone_value"=>"America/Scoresbysund","created_at"=> $now,],
        ["name"=>"Shiprock,USA","zone_value"=>"America/Shiprock","created_at"=> $now,],
        ["name"=>"Sitka,USA","zone_value"=>"America/Sitka","created_at"=> $now,],
        ["name"=>"St. Barts,AST","zone_value"=>"America/St_Barthelemy","created_at"=> $now,],
        ["name"=>" St. John's,CA","zone_value"=>"America/St_Johns","created_at"=> $now,],
        ["name"=>"Saint Kitts and Nevis","zone_value"=>"America/St_Kitts","created_at"=> $now,],
        ["name"=>"Saint Lucia","zone_value"=>"America/St_Lucia","created_at"=> $now,],
        ["name"=>"Saint Thomas","zone_value"=>"America/St_Thomas","created_at"=> $now,],
        ["name"=>"St. Vincent & Grenadines,VC","zone_value"=>"America/St_Vincent","created_at"=> $now,],
        ["name"=>"Swift Current,CA","zone_value"=>"America/Swift_Current","created_at"=> $now,],
        ["name"=>"Honduras,HN","zone_value"=>"America/Tegucigalpa","created_at"=> $now,],
        ["name"=>"Thule ,GL","zone_value"=>"America/Thule","created_at"=> $now,],
        ["name"=>"Thunder Bay,CA","zone_value"=>"America/Thunder_Bay","created_at"=> $now,],
        ["name"=>"Tijuana,MX","zone_value"=>"America/Tijuana","created_at"=> $now,],
        ["name"=>"Toronto,CA","zone_value"=>"America/Toronto","created_at"=> $now,],
        ["name"=>"Tortola ","zone_value"=>"America/Tortola","created_at"=> $now,],
        ["name"=>"Vancouver,CA","zone_value"=>"America/Vancouver","created_at"=> $now,],
        ["name"=>"Virgin,USA","zone_value"=>"America/Virgin","created_at"=> $now,],
        ["name"=>"Whitehorse,CA","zone_value"=>"America/Whitehorse","created_at"=> $now,],
        ["name"=>"Winnipeg,CA","zone_value"=>"America/Winnipeg","created_at"=> $now,],
        ["name"=>"Yakutat,USA","zone_value"=>"America/Yakutat","created_at"=> $now,],
        ["name"=>"Yellowknife,CA","zone_value"=>"America/Yellowknife","created_at"=> $now,],
        ["name"=>"Casey,AQ","zone_value"=>"Antarctica/Casey","created_at"=> $now,],
        ["name"=>"Davis,AQ","zone_value"=>"Antarctica/Davis","created_at"=> $now,],
        ["name"=>"DumontDUrville,AQ","zone_value"=>"Antarctica/DumontDUrville","created_at"=> $now,],
        ["name"=>"Macquarie ","zone_value"=>"Antarctica/Macquarie","created_at"=> $now,],
        ["name"=>"Mawson ,AQ","zone_value"=>"Antarctica/Mawson","created_at"=> $now,],
        ["name"=>"McMurdo,NZST","zone_value"=>"Antarctica/McMurdo","created_at"=> $now,],
        ["name"=>"Palmer ,AQ","zone_value"=>"Antarctica/Palmer","created_at"=> $now,],
        ["name"=>"Rothera ,AQ","zone_value"=>"Antarctica/Rothera","created_at"=> $now,],
        ["name"=>"South Pole,NZST","zone_value"=>"Antarctica/South_Pole","created_at"=> $now,],
        ["name"=>"Syowa ,AQ","zone_value"=>"Antarctica/Syowa","created_at"=> $now,],
        ["name"=>"Troll ","zone_value"=>"Antarctica/Troll","created_at"=> $now,],
        ["name"=>"Lake Vostok","zone_value"=>"Antarctica/Vostok","created_at"=> $now,],
        ["name"=>"Svalbard & Jan Mayen ,SJ","zone_value"=>"Arctic/Longyearbyen","created_at"=> $now,],
        ["name"=>"Yemen","zone_value"=>"Asia/Aden","created_at"=> $now,],
        ["name"=>"Almaty ,KZ","zone_value"=>"Asia/Almaty","created_at"=> $now,],
        ["name"=>"Amman,JO","zone_value"=>"Asia/Amman","created_at"=> $now,],
        ["name"=>"Anadyr,RU","zone_value"=>"Asia/Anadyr","created_at"=> $now,],
        ["name"=>"Aktau,KZ","zone_value"=>"Asia/Aqtau","created_at"=> $now,],
        ["name"=>"Aqtobe,KZ","zone_value"=>"Asia/Aqtobe","created_at"=> $now,],
        ["name"=>"Ashgabat,TM","zone_value"=>"Asia/Ashgabat","created_at"=> $now,],
        ["name"=>"Ashkhabad ,TM","zone_value"=>"Asia/Ashkhabad","created_at"=> $now,],
        ["name"=>"Atyrau,KZ","zone_value"=>"Asia/Atyrau","created_at"=> $now,],
        ["name"=>"Iraq ,IQ","zone_value"=>"Asia/Baghdad","created_at"=> $now,],
        ["name"=>"Bahrain ,BH","zone_value"=>"Asia/Bahrain","created_at"=> $now,],
        ["name"=>"Azerbaijan ,AZ","zone_value"=>"Asia/Baku","created_at"=> $now,],
        ["name"=>"Thailand ,TH","zone_value"=>"Asia/Bangkok","created_at"=> $now,],
        ["name"=>"Barnaul,RU","zone_value"=>"Asia/Barnaul","created_at"=> $now,],
        ["name"=>"Lebanon ,LB","zone_value"=>"Asia/Beirut","created_at"=> $now,],
        ["name"=>"Kyrgyzstan ,KG","zone_value"=>"Asia/Bishkek","created_at"=> $now,],
        ["name"=>"Brunei,BN","zone_value"=>"Asia/Brunei","created_at"=> $now,],
        ["name"=>"India ,IN","zone_value"=>"Asia/Calcutta","created_at"=> $now,],
        ["name"=>"Chita,RU","zone_value"=>"Asia/Chita","created_at"=> $now,],
        ["name"=>"Choibalsan ,MN","zone_value"=>"Asia/Choibalsan","created_at"=> $now,],
        ["name"=>"Chongqing,CN","zone_value"=>"Asia/Chongqing","created_at"=> $now,],
        ["name"=>"Chungking","zone_value"=>"Asia/Chungking","created_at"=> $now,],
        ["name"=>"Sri Lanka,LK","zone_value"=>"Asia/Colombo","created_at"=> $now,],
        ["name"=>"Dacca","zone_value"=>"Asia/Dacca","created_at"=> $now,],
        ["name"=>"Syria ,SY","zone_value"=>"Asia/Damascus","created_at"=> $now,],
        ["name"=>"Dhaka,BD","zone_value"=>"Asia/Dhaka","created_at"=> $now,],
        ["name"=>"Timor Leste,TL","zone_value"=>"Asia/Dili","created_at"=> $now,],
        ["name"=>"Dubai ,UAE","zone_value"=>"Asia/Dubai","created_at"=> $now,],
        ["name"=>"Tajikistan,TJ","zone_value"=>"Asia/Dushanbe","created_at"=> $now,],
        ["name"=>"Famagusta","zone_value"=>"Asia/Famagusta","created_at"=> $now,],
        ["name"=>"Palestine ,PS","zone_value"=>"Asia/Gaza","created_at"=> $now,],
        ["name"=>"Harbin,CN","zone_value"=>"Asia/Harbin","created_at"=> $now,],
        ["name"=>"Hebron ","zone_value"=>"Asia/Hebron","created_at"=> $now,],
        ["name"=>"Hong Kong,HK","zone_value"=>"Asia/Hong_Kong","created_at"=> $now,],
        ["name"=>"Hovd,MN","zone_value"=>"Asia/Hovd","created_at"=> $now,],
        ["name"=>"Vietnam ,VN","zone_value"=>"Asia/Ho_Chi_Minh","created_at"=> $now,],
        ["name"=>"Irkutsk,RU","zone_value"=>"Asia/Irkutsk","created_at"=> $now,],
        ["name"=>"Turkey ,TR","zone_value"=>"Asia/Istanbul","created_at"=> $now,],
        ["name"=>"Jakarta,ID","zone_value"=>"Asia/Jakarta","created_at"=> $now,],
        ["name"=>"Jayapura,ID","zone_value"=>"Asia/Jayapura","created_at"=> $now,],
        ["name"=>"Jerusalem,IL","zone_value"=>"Asia/Jerusalem","created_at"=> $now,],
        ["name"=>"Afghanistan ,AF","zone_value"=>"Asia/Kabul","created_at"=> $now,],
        ["name"=>"Kamchatka,RU","zone_value"=>"Asia/Kamchatka","created_at"=> $now,],
        ["name"=>"Pakistan ,PK","zone_value"=>"Asia/Karachi","created_at"=> $now,],
        ["name"=>"Kashgar,CN","zone_value"=>"Asia/Kashgar","created_at"=> $now,],
        ["name"=>"Nepal ,NP","zone_value"=>"Asia/Kathmandu","created_at"=> $now,],
        ["name"=>"Katmandu ","zone_value"=>"Asia/Katmandu","created_at"=> $now,],
        ["name"=>"Khandyga ","zone_value"=>"Asia/Khandyga","created_at"=> $now,],
        ["name"=>"Kolkata,IN","zone_value"=>"Asia/Kolkata","created_at"=> $now,],
        ["name"=>"Krasnoyarsk,RU","zone_value"=>"Asia/Krasnoyarsk","created_at"=> $now,],
        ["name"=>" Kuala Lumpu ,MY","zone_value"=>"Asia/Kuala_Lumpur","created_at"=> $now,],
        ["name"=>"Kuching,MY","zone_value"=>"Asia/Kuching","created_at"=> $now,],
        ["name"=>"Kuwait ,KW","zone_value"=>"Asia/Kuwait","created_at"=> $now,],
        ["name"=>"Macao","zone_value"=>"Asia/Macao","created_at"=> $now,],
        ["name"=>"Macau ,MO","zone_value"=>"Asia/Macau","created_at"=> $now,],
        ["name"=>"Magadan,RU","zone_value"=>"Asia/Magadan","created_at"=> $now,],
        ["name"=>"Makassar,ID","zone_value"=>"Asia/Makassar","created_at"=> $now,],
        ["name"=>"Philippines,PH","zone_value"=>"Asia/Manila","created_at"=> $now,],
        ["name"=>"Muscat,OM","zone_value"=>"Asia/Muscat","created_at"=> $now,],
        ["name"=>"Cyprus ,CY","zone_value"=>"Asia/Nicosia","created_at"=> $now,],
        ["name"=>"Novokuznetsk ,RU","zone_value"=>"Asia/Novokuznetsk","created_at"=> $now,],
        ["name"=>"Novosibirsk,RU","zone_value"=>"Asia/Novosibirsk","created_at"=> $now,],
        ["name"=>"Omsk,RU","zone_value"=>"Asia/Omsk","created_at"=> $now,],
        ["name"=>"Oral ","zone_value"=>"Asia/Oral","created_at"=> $now,],
        ["name"=>"Phnom Penh,KH","zone_value"=>"Asia/Phnom_Penh","created_at"=> $now,],
        ["name"=>"Pontianak ,ID","zone_value"=>"Asia/Pontianak","created_at"=> $now,],
        ["name"=>"North Korea,KP","zone_value"=>"Asia/Pyongyang","created_at"=> $now,],
        ["name"=>"Qatar ,QA","zone_value"=>"Asia/Qatar","created_at"=> $now,],
        ["name"=>"Qostanay ","zone_value"=>"Asia/Qostanay","created_at"=> $now,],
        ["name"=>"Qyzylorda ","zone_value"=>"Asia/Qyzylorda","created_at"=> $now,],
        ["name"=>"Rangoon ","zone_value"=>"Asia/Rangoon","created_at"=> $now,],
        ["name"=>"Saudi Arabia,SA","zone_value"=>"Asia/Riyadh","created_at"=> $now,],
        ["name"=>"Vietnam ,VN","zone_value"=>"Asia/Saigon","created_at"=> $now,],
        ["name"=>"Sakhalin ","zone_value"=>"Asia/Sakhalin","created_at"=> $now,],
        ["name"=>"Uzbekistan ","zone_value"=>"Asia/Samarkand","created_at"=> $now,],
        ["name"=>"South Korea,KR","zone_value"=>"Asia/Seoul","created_at"=> $now,],
        ["name"=>"Shanghai,CN","zone_value"=>"Asia/Shanghai","created_at"=> $now,],
        ["name"=>"Singapore ,SG","zone_value"=>"Asia/Singapore","created_at"=> $now,],
        ["name"=>"Srednekolymsk,RU","zone_value"=>"Asia/Srednekolymsk","created_at"=> $now,],
        ["name"=>"Taiwan ,TW","zone_value"=>"Asia/Taipei","created_at"=> $now,],
        ["name"=>"Uzbekistan ,UZ","zone_value"=>"Asia/Tashkent","created_at"=> $now,],
        ["name"=>"Georgia ,GE","zone_value"=>"Asia/Tbilisi","created_at"=> $now,],
        ["name"=>"Iran ,IR","zone_value"=>"Asia/Tehran","created_at"=> $now,],
        ["name"=>"Tel Aviv Yafo","zone_value"=>"Asia/Tel_Aviv","created_at"=> $now,],
        ["name"=>"Thimbu ","zone_value"=>"Asia/Thimbu","created_at"=> $now,],
        ["name"=>"Bhutan ,BT","zone_value"=>"Asia/Thimphu","created_at"=> $now,],
        ["name"=>"Japan ,JP","zone_value"=>"Asia/Tokyo","created_at"=> $now,],
        ["name"=>"Tomsk,RU","zone_value"=>"Asia/Tomsk","created_at"=> $now,],
        ["name"=>"Makassar,ID","zone_value"=>"Asia/Ujung_Pandang","created_at"=> $now,],
        ["name"=>"Ulaanbaatar,MN","zone_value"=>"Asia/Ulaanbaatar","created_at"=> $now,],
        ["name"=>"Ürümqi,CN","zone_value"=>"Asia/Urumqi","created_at"=> $now,],
        ["name"=>"Sakha Republic,RU","zone_value"=>"Asia/Ust-Nera","created_at"=> $now,],
        ["name"=>"Laos,LA","zone_value"=>"Asia/Vientiane","created_at"=> $now,],
        ["name"=>"Vladivostok ,RU","zone_value"=>"Asia/Vladivostok","created_at"=> $now,],
        ["name"=>"Yakutsk,RU","zone_value"=>"Asia/Yakutsk","created_at"=> $now,],
        ["name"=>"Yangon","zone_value"=>"Asia/Yangon","created_at"=> $now,],
        ["name"=>"Yekaterinburg,RU","zone_value"=>"Asia/Yekaterinburg","created_at"=> $now,],
        ["name"=>"Armenia ,AM","zone_value"=>"Asia/Yerevan","created_at"=> $now,],
        ["name"=>"Azores,PT","zone_value"=>"Atlantic/Azores","created_at"=> $now,],
        ["name"=>"Bermuda,BM","zone_value"=>"Atlantic/Bermuda","created_at"=> $now,],
        ["name"=>"Canary,ES","zone_value"=>"Atlantic/Canary","created_at"=> $now,],
        ["name"=>"Cape Verde,CV","zone_value"=>"Atlantic/Cape_Verde","created_at"=> $now,],
        ["name"=>"Faroe Islands,FO","zone_value"=>"Atlantic/Faeroe","created_at"=> $now,],
        ["name"=>"Faroe","zone_value"=>"Atlantic/Faroe","created_at"=> $now,],
        ["name"=>"Jan Mayen","zone_value"=>"Atlantic/Jan_Mayen","created_at"=> $now,],
        ["name"=>"Madeira","zone_value"=>"Atlantic/Madeira","created_at"=> $now,],
        ["name"=>"Iceland ,IS","zone_value"=>"Atlantic/Reykjavik","created_at"=> $now,],
        ["name"=>"South Georgia And South Sandwich Islands,GS","zone_value"=>"Atlantic/South_Georgia","created_at"=> $now,],
        ["name"=>"Falkland Islands,FK","zone_value"=>"Atlantic/Stanley","created_at"=> $now,],
        ["name"=>"St. Helena,SH","zone_value"=>"Atlantic/St_Helena","created_at"=> $now,],
        ["name"=>"Australian Capital Territory,AU","zone_value"=>"Australia/ACT","created_at"=> $now,],
        ["name"=>"Adelaide,AU","zone_value"=>"Australia/Adelaide","created_at"=> $now,],
        ["name"=>"Brisbane,AU","zone_value"=>"Australia/Brisbane","created_at"=> $now,],
        ["name"=>" Broken Hill NSW,AU","zone_value"=>"Australia/Broken_Hill","created_at"=> $now,],
        ["name"=>"Canberra ,AU","zone_value"=>"Australia/Canberra","created_at"=> $now,],
        ["name"=>"Currie TAS,AU","zone_value"=>"Australia/Currie","created_at"=> $now,],
        ["name"=>"Darwin,AU","zone_value"=>"Australia/Darwin","created_at"=> $now,],
        ["name"=>"Eucla WA,AU","zone_value"=>"Australia/Eucla","created_at"=> $now,],
        ["name"=>"Hobart,AU","zone_value"=>"Australia/Hobart","created_at"=> $now,],
        ["name"=>"LHI,AU","zone_value"=>"Australia/LHI","created_at"=> $now,],
        ["name"=>"Lindeman Island,AU","zone_value"=>"Australia/Lindeman","created_at"=> $now,],
        ["name"=>"Lord Howe,AU","zone_value"=>"Australia/Lord_Howe","created_at"=> $now,],
        ["name"=>"Melbourne ,AU","zone_value"=>"Australia/Melbourne","created_at"=> $now,],
        ["name"=>"Australia/North ,AU","zone_value"=>"Australia/North","created_at"=> $now,],
        ["name"=>"Victoria and Tasmania,AU","zone_value"=>"Australia/NSW","created_at"=> $now,],
        ["name"=>"Perth WA,AU","zone_value"=>"Australia/Perth","created_at"=> $now,],
        ["name"=>"Queensland,AU","zone_value"=>"Australia/Queensland","created_at"=> $now,],
        ["name"=>"South Australia,AU","zone_value"=>"Australia/South","created_at"=> $now,],
        ["name"=>"Sydney NSW,AU","zone_value"=>"Australia/Sydney","created_at"=> $now,],
        ["name"=>"Tasmania,AU","zone_value"=>"Australia/Tasmania","created_at"=> $now,],
        ["name"=>"Victoria,AU","zone_value"=>"Australia/Victoria","created_at"=> $now,],
        ["name"=>"Western Australia,AWST","zone_value"=>"Australia/West","created_at"=> $now,],
        ["name"=>"Yancowinna ,AU","zone_value"=>"Australia/Yancowinna","created_at"=> $now,],
        ["name"=>"Acre,BR","zone_value"=>"Brazil/Acre","created_at"=> $now,],
        ["name"=>"De Noronha,BR","zone_value"=>"Brazil/DeNoronha","created_at"=> $now,],
        ["name"=>"Brazil East,BR","zone_value"=>"Brazil/East","created_at"=> $now,],
        ["name"=>"Brazil West,BR","zone_value"=>"Brazil/West","created_at"=> $now,],
        ["name"=>"Atlantic ,CA","zone_value"=>"Canada/Atlantic","created_at"=> $now,],
        ["name"=>"Canada Central ,CA","zone_value"=>"Canada/Central","created_at"=> $now,],
        ["name"=>"Canada Eastern,CA","zone_value"=>"Canada/Eastern","created_at"=> $now,],
        ["name"=>"Canada Mountain,CA","zone_value"=>"Canada/Mountain","created_at"=> $now,],
        ["name"=>"Canada Newfoundland,CA","zone_value"=>"Canada/Newfoundland","created_at"=> $now,],
        ["name"=>"Canada Pacific,CA","zone_value"=>"Canada/Pacific","created_at"=> $now,],
        ["name"=>"Canada Saskatchewan,CA","zone_value"=>"Canada/Saskatchewan","created_at"=> $now,],
        ["name"=>"Canada Yukon,CA","zone_value"=>"Canada/Yukon","created_at"=> $now,],
        ["name"=>"Central European Time,CET","zone_value"=>"CET","created_at"=> $now,],
        ["name"=>"Magallanes and Chilean Antarctica","zone_value"=>"Chile/Continental","created_at"=> $now,],
        ["name"=>"Easter Island","zone_value"=>"Chile/EasterIsland","created_at"=> $now,],
        ["name"=>"US Central Time","zone_value"=>"CST6CDT","created_at"=> $now,],
        ["name"=>"Cuba,CU","zone_value"=>"Cuba","created_at"=> $now,],
        ["name"=>"Eastern European Time,EET","zone_value"=>"EET","created_at"=> $now,],
        ["name"=>"Egypt,EG","zone_value"=>"Egypt","created_at"=> $now,],
        ["name"=>"Eire","zone_value"=>"Eire","created_at"=> $now,],
        ["name"=>"Eastern Time,ET","zone_value"=>"EST","created_at"=> $now,],
        ["name"=>"US Eastern Time","zone_value"=>"EST5EDT","created_at"=> $now,],
        ["name"=>"Etc/GMT","zone_value"=>"Etc/GMT","created_at"=> $now,],
        ["name"=>"Etc/GMT+0","zone_value"=>"Etc/GMT+0","created_at"=> $now,],
        ["name"=>"Etc/GMT+1","zone_value"=>"Etc/GMT+1","created_at"=> $now,],
        ["name"=>"Etc/GMT+10","zone_value"=>"Etc/GMT+10","created_at"=> $now,],
        ["name"=>"Etc/GMT+11","zone_value"=>"Etc/GMT+11","created_at"=> $now,],
        ["name"=>"Etc/GMT+12","zone_value"=>"Etc/GMT+12","created_at"=> $now,],
        ["name"=>"Etc/GMT+2","zone_value"=>"Etc/GMT+2","created_at"=> $now,],
        ["name"=>"Etc/GMT+3","zone_value"=>"Etc/GMT+3","created_at"=> $now,],
        ["name"=>"Etc/GMT+4","zone_value"=>"Etc/GMT+4","created_at"=> $now,],
        ["name"=>"Etc/GMT+5","zone_value"=>"Etc/GMT+5","created_at"=> $now,],
        ["name"=>"Etc/GMT+6","zone_value"=>"Etc/GMT+6","created_at"=> $now,],
        ["name"=>"Etc/GMT+7","zone_value"=>"Etc/GMT+7","created_at"=> $now,],
        ["name"=>"Etc/GMT+8","zone_value"=>"Etc/GMT+8","created_at"=> $now,],
        ["name"=>"Etc/GMT+9","zone_value"=>"Etc/GMT+9","created_at"=> $now,],
        ["name"=>"Etc/GMT-0","zone_value"=>"Etc/GMT-0","created_at"=> $now,],
        ["name"=>"Etc/GMT-1","zone_value"=>"Etc/GMT-1","created_at"=> $now,],
        ["name"=>"Etc/GMT-10","zone_value"=>"Etc/GMT-10","created_at"=> $now,],
        ["name"=>"Etc/GMT-11","zone_value"=>"Etc/GMT-11","created_at"=> $now,],
        ["name"=>"Etc/GMT-12","zone_value"=>"Etc/GMT-12","created_at"=> $now,],
        ["name"=>"Etc/GMT-13","zone_value"=>"Etc/GMT-13","created_at"=> $now,],
        ["name"=>"Etc/GMT-14","zone_value"=>"Etc/GMT-14","created_at"=> $now,],
        ["name"=>"Etc/GMT-2","zone_value"=>"Etc/GMT-2","created_at"=> $now,],
        ["name"=>"Etc/GMT-3","zone_value"=>"Etc/GMT-3","created_at"=> $now,],
        ["name"=>"Etc/GMT-4","zone_value"=>"Etc/GMT-4","created_at"=> $now,],
        ["name"=>"Etc/GMT-5","zone_value"=>"Etc/GMT-5","created_at"=> $now,],
        ["name"=>"Etc/GMT-6","zone_value"=>"Etc/GMT-6","created_at"=> $now,],
        ["name"=>"Etc/GMT-7","zone_value"=>"Etc/GMT-7","created_at"=> $now,],
        ["name"=>"Etc/GMT-8","zone_value"=>"Etc/GMT-8","created_at"=> $now,],
        ["name"=>"Etc/GMT-9","zone_value"=>"Etc/GMT-9","created_at"=> $now,],
        ["name"=>"Etc/GMT0","zone_value"=>"Etc/GMT0","created_at"=> $now,],
        ["name"=>"Etc/Greenwich","zone_value"=>"Etc/Greenwich","created_at"=> $now,],
        ["name"=>"Etc/UCT","zone_value"=>"Etc/UCT","created_at"=> $now,],
        ["name"=>"Etc/Universal","zone_value"=>"Etc/Universal","created_at"=> $now,],
        ["name"=>"Etc/UTC","zone_value"=>"Etc/UTC","created_at"=> $now,],
        ["name"=>"Etc/Zulu","zone_value"=>"Etc/Zulu","created_at"=> $now,],
        ["name"=>"Netherlands ,NL","zone_value"=>"Europe/Amsterdam","created_at"=> $now,],
        ["name"=>"Andorra,AD","zone_value"=>"Europe/Andorra","created_at"=> $now,],
        ["name"=>"Russian Federation,RU","zone_value"=>"Europe/Astrakhan","created_at"=> $now,],
        ["name"=>"Greece ,GR","zone_value"=>"Europe/Athens","created_at"=> $now,],
        ["name"=>"Belfast,UK","zone_value"=>"Europe/Belfast","created_at"=> $now,],
        ["name"=>"Serbia,RS","zone_value"=>"Europe/Belgrade","created_at"=> $now,],
        ["name"=>"Berlin ,DE","zone_value"=>"Europe/Berlin","created_at"=> $now,],
        ["name"=>"Bratislava","zone_value"=>"Europe/Bratislava","created_at"=> $now,],
        ["name"=>"Belgium,BE","zone_value"=>"Europe/Brussels","created_at"=> $now,],
        ["name"=>"Romania ,RO","zone_value"=>"Europe/Bucharest","created_at"=> $now,],
        ["name"=>"Hungary ,HU","zone_value"=>"Europe/Budapest","created_at"=> $now,],
        ["name"=>"Busingen ,DE","zone_value"=>"Europe/Busingen","created_at"=> $now,],
        ["name"=>"Moldova ,MD","zone_value"=>"Europe/Chisinau","created_at"=> $now,],
        ["name"=>"Denmark ,DK","zone_value"=>"Europe/Copenhagen","created_at"=> $now,],
        ["name"=>"Ireland,IE","zone_value"=>"Europe/Dublin","created_at"=> $now,],
        ["name"=>"Gibraltar,GI","zone_value"=>"Europe/Gibraltar","created_at"=> $now,],
        ["name"=>"Guernsey ,GG","zone_value"=>"Europe/Guernsey","created_at"=> $now,],
        ["name"=>"Helsinki,AX","zone_value"=>"Europe/Helsinki","created_at"=> $now,],
        ["name"=>"Isle of Man","zone_value"=>"Europe/Isle_of_Man","created_at"=> $now,],
        ["name"=>"Turkey ,TR","zone_value"=>"Europe/Istanbul","created_at"=> $now,],
        ["name"=>"Jersey ","zone_value"=>"Europe/Jersey","created_at"=> $now,],
        ["name"=>"Kaliningrad,RU","zone_value"=>"Europe/Kaliningrad","created_at"=> $now,],
        ["name"=>"Ukraine ,UA","zone_value"=>"Europe/Kiev","created_at"=> $now,],
        ["name"=>"Kirov,RU","zone_value"=>"Europe/Kirov","created_at"=> $now,],
        ["name"=>"Lisbon,PT","zone_value"=>"Europe/Lisbon","created_at"=> $now,],
        ["name"=>"Ljubljana","zone_value"=>"Europe/Ljubljana","created_at"=> $now,],
        ["name"=>"London,UK","zone_value"=>"Europe/London","created_at"=> $now,],
        ["name"=>"Luxembourg,LU","zone_value"=>"Europe/Luxembourg","created_at"=> $now,],
        ["name"=>"Madrid,ES","zone_value"=>"Europe/Madrid","created_at"=> $now,],
        ["name"=>"Malta,MT","zone_value"=>"Europe/Malta","created_at"=> $now,],
        ["name"=>"Mariehamn","zone_value"=>"Europe/Mariehamn","created_at"=> $now,],
        ["name"=>"Minsk,BY","zone_value"=>"Europe/Minsk","created_at"=> $now,],
        ["name"=>"Monaco,MC","zone_value"=>"Europe/Monaco","created_at"=> $now,],
        ["name"=>"Moscow,RU","zone_value"=>"Europe/Moscow","created_at"=> $now,],
        ["name"=>"Nicosia ","zone_value"=>"Europe/Nicosia","created_at"=> $now,],
        ["name"=>"Norway ,NO","zone_value"=>"Europe/Oslo","created_at"=> $now,],
        ["name"=>"France,FR","zone_value"=>"Europe/Paris","created_at"=> $now,],
        ["name"=>"Podgorica","zone_value"=>"Europe/Podgorica","created_at"=> $now,],
        ["name"=>"Czech ,CZ","zone_value"=>"Europe/Prague","created_at"=> $now,],
        ["name"=>"Latvia ,LV","zone_value"=>"Europe/Riga","created_at"=> $now,],
        ["name"=>"Italy ,IT","zone_value"=>"Europe/Rome","created_at"=> $now,],
        ["name"=>"Samara,RU","zone_value"=>"Europe/Samara","created_at"=> $now,],
        ["name"=>"San Marino,SM","zone_value"=>"Europe/San_Marino","created_at"=> $now,],
        ["name"=>"Sarajevo","zone_value"=>"Europe/Sarajevo","created_at"=> $now,],
        ["name"=>"Saratov Oblast,RU","zone_value"=>"Europe/Saratov","created_at"=> $now,],
        ["name"=>"Simferopol ","zone_value"=>"Europe/Simferopol","created_at"=> $now,],
        ["name"=>"Skopje","zone_value"=>"Europe/Skopje","created_at"=> $now,],
        ["name"=>"Bulgaria ,BG","zone_value"=>"Europe/Sofia","created_at"=> $now,],
        ["name"=>"Sweden ,SE","zone_value"=>"Europe/Stockholm","created_at"=> $now,],
        ["name"=>"Estonia ,EE","zone_value"=>"Europe/Tallinn","created_at"=> $now,],
        ["name"=>"Albania ,AL","zone_value"=>"Europe/Tirane","created_at"=> $now,],
        ["name"=>"Tiraspol","zone_value"=>"Europe/Tiraspol","created_at"=> $now,],
        ["name"=>"Ulyanovsk,RU","zone_value"=>"Europe/Ulyanovsk","created_at"=> $now,],
        ["name"=>"Uzhhorod,UA","zone_value"=>"Europe/Uzhgorod","created_at"=> $now,],
        ["name"=>"Vaduz","zone_value"=>"Europe/Vaduz","created_at"=> $now,],
        ["name"=>"Vatican City","zone_value"=>"Europe/Vatican","created_at"=> $now,],
        ["name"=>"Austria ,AT","zone_value"=>"Europe/Vienna","created_at"=> $now,],
        ["name"=>"Lithuania ,LT","zone_value"=>"Europe/Vilnius","created_at"=> $now,],
        ["name"=>"Volgograd ","zone_value"=>"Europe/Volgograd","created_at"=> $now,],
        ["name"=>"Poland ,PL","zone_value"=>"Europe/Warsaw","created_at"=> $now,],
        ["name"=>"Zagreb","zone_value"=>"Europe/Zagreb","created_at"=> $now,],
        ["name"=>"Zaporizhzhia","zone_value"=>"Europe/Zaporozhye","created_at"=> $now,],
        ["name"=>"Switzerland,CH","zone_value"=>"Europe/Zurich","created_at"=> $now,],
        ["name"=>"United Kingdom,GB","zone_value"=>"GB","created_at"=> $now,],
        ["name"=>"Caighdeánach ","zone_value"=>"GB-Eire","created_at"=> $now,],
        ["name"=>"GMT","zone_value"=>"GMT","created_at"=> $now,],
        ["name"=>"GMT+0","zone_value"=>"GMT+0","created_at"=> $now,],
        ["name"=>"GMT-0","zone_value"=>"GMT-0","created_at"=> $now,],
        ["name"=>"GMT0","zone_value"=>"GMT0","created_at"=> $now,],
        ["name"=>"London,UK","zone_value"=>"Greenwich","created_at"=> $now,],
        ["name"=>"Hongkong","zone_value"=>"Hongkong","created_at"=> $now,],
        ["name"=>"Hawaii Standard Time,HST","zone_value"=>"HST","created_at"=> $now,],
        ["name"=>"Iceland,IS","zone_value"=>"Iceland","created_at"=> $now,],
        ["name"=>"Antananarivo ","zone_value"=>"Indian/Antananarivo","created_at"=> $now,],
        ["name"=>"British Indian Ocean Territory,IO","zone_value"=>"Indian/Chagos","created_at"=> $now,],
        ["name"=>"Christmas Island,CX","zone_value"=>"Indian/Christmas","created_at"=> $now,],
        ["name"=>"Cocos ,CC","zone_value"=>"Indian/Cocos","created_at"=> $now,],
        ["name"=>"Comoro","zone_value"=>"Indian/Comoro","created_at"=> $now,],
        ["name"=>"French Southern Territories,TF","zone_value"=>"Indian/Kerguelen","created_at"=> $now,],
        ["name"=>"Seychelles,SC","zone_value"=>"Indian/Mahe","created_at"=> $now,],
        ["name"=>"Maldives,MV","zone_value"=>"Indian/Maldives","created_at"=> $now,],
        ["name"=>"Mauritius ,MU","zone_value"=>"Indian/Mauritius","created_at"=> $now,],
        ["name"=>"Mayotte ","zone_value"=>"Indian/Mayotte","created_at"=> $now,],
        ["name"=>"Réunion ,RE","zone_value"=>"Indian/Reunion","created_at"=> $now,],
        ["name"=>"Iran,IR","zone_value"=>"Iran","created_at"=> $now,],
        ["name"=>"Israel,IL","zone_value"=>"Israel","created_at"=> $now,],
        ["name"=>"Jamaica,JM","zone_value"=>"Jamaica","created_at"=> $now,],
        ["name"=>"Japan,JP","zone_value"=>"Japan","created_at"=> $now,],
        ["name"=>"Kwajalein,MH","zone_value"=>"Kwajalein","created_at"=> $now,],
        ["name"=>"Libya,LY","zone_value"=>"Libya","created_at"=> $now,],
        ["name"=>"Middle European Time,MET","zone_value"=>"MET","created_at"=> $now,],
        ["name"=>" Baja California,MX","zone_value"=>"Mexico/BajaNorte","created_at"=> $now,],
        ["name"=>" Baja California Sur,MX","zone_value"=>"Mexico/BajaSur","created_at"=> $now,],
        ["name"=>"capital Mexico City,MX","zone_value"=>"Mexico/General","created_at"=> $now,],
        ["name"=>"Mountain Time,MST","zone_value"=>"MST","created_at"=> $now,],
        ["name"=>"US Mountain Time","zone_value"=>"MST7MDT","created_at"=> $now,],
        ["name"=>"Navajo","zone_value"=>"Navajo","created_at"=> $now,],
        ["name"=>"New Zealand,NZ","zone_value"=>"NZ","created_at"=> $now,],
        ["name"=>"Chatham Island Standard Time,CHAST","zone_value"=>"NZ-CHAT","created_at"=> $now,],
        ["name"=>"Samoa,WS","zone_value"=>"Pacific/Apia","created_at"=> $now,],
        ["name"=>"Auckland,NZ","zone_value"=>"Pacific/Auckland","created_at"=> $now,],
        ["name"=>"Bougainville Island","zone_value"=>"Pacific/Bougainville","created_at"=> $now,],
        ["name"=>"Chatham ,NZ","zone_value"=>"Pacific/Chatham","created_at"=> $now,],
        ["name"=>"Chuuk,FM","zone_value"=>"Pacific/Chuuk","created_at"=> $now,],
        ["name"=>"Easter,CL","zone_value"=>"Pacific/Easter","created_at"=> $now,],
        ["name"=>"Vanuatu,VU","zone_value"=>"Pacific/Efate","created_at"=> $now,],
        ["name"=>"Enderbury,UM","zone_value"=>"Pacific/Enderbury","created_at"=> $now,],
        ["name"=>"Fakaofo,TK","zone_value"=>"Pacific/Fakaofo","created_at"=> $now,],
        ["name"=>"Fiji,FJ","zone_value"=>"Pacific/Fiji","created_at"=> $now,],
        ["name"=>"Tuvalu,TV","zone_value"=>"Pacific/Funafuti","created_at"=> $now,],
        ["name"=>"Galapagos,EC","zone_value"=>"Pacific/Galapagos","created_at"=> $now,],
        ["name"=>"Gambier,PF","zone_value"=>"Pacific/Gambier","created_at"=> $now,],
        ["name"=>"Solomon Islands,SB","zone_value"=>"Pacific/Guadalcanal","created_at"=> $now,],
        ["name"=>"Guam,GU","zone_value"=>"Pacific/Guam","created_at"=> $now,],
        ["name"=>"Honolulu,US","zone_value"=>"Pacific/Honolulu","created_at"=> $now,],
        ["name"=>"United States Minor Outlying Islands,US","zone_value"=>"Pacific/Johnston","created_at"=> $now,],
        ["name"=>"Kanton ","zone_value"=>"Pacific/Kanton","created_at"=> $now,],
        ["name"=>"Kiritimati ","zone_value"=>"Pacific/Kiritimati","created_at"=> $now,],
        ["name"=>"Kosrae,FM","zone_value"=>"Pacific/Kosrae","created_at"=> $now,],
        ["name"=>"Kwajalein,MH","zone_value"=>"Pacific/Kwajalein","created_at"=> $now,],
        ["name"=>"Majuro,MH","zone_value"=>"Pacific/Majuro","created_at"=> $now,],
        ["name"=>"Marquesas,PF","zone_value"=>"Pacific/Marquesas","created_at"=> $now,],
        ["name"=>"Midway ","zone_value"=>"Pacific/Midway","created_at"=> $now,],
        ["name"=>"Nauru,NR","zone_value"=>"Pacific/Nauru","created_at"=> $now,],
        ["name"=>"Niue,NU","zone_value"=>"Pacific/Niue","created_at"=> $now,],
        ["name"=>"Norfolk Island,NF","zone_value"=>"Pacific/Norfolk","created_at"=> $now,],
        ["name"=>"New Caledonia,NC","zone_value"=>"Pacific/Noumea","created_at"=> $now,],
        ["name"=>"Pago Pago,NS","zone_value"=>"Pacific/Pago_Pago","created_at"=> $now,],
        ["name"=>"Palau,PW","zone_value"=>"Pacific/Palau","created_at"=> $now,],
        ["name"=>"Pitcairn Islands,PN","zone_value"=>"Pacific/Pitcairn","created_at"=> $now,],
        ["name"=>"Micronesia,FM","zone_value"=>"Pacific/Pohnpei","created_at"=> $now,],
        ["name"=>"Ponape ","zone_value"=>"Pacific/Ponape","created_at"=> $now,],
        ["name"=>"Papua New Guinea,PG","zone_value"=>"Pacific/Port_Moresby","created_at"=> $now,],
        ["name"=>"Cook Islands,CK","zone_value"=>"Pacific/Rarotonga","created_at"=> $now,],
        ["name"=>"Saipan ","zone_value"=>"Pacific/Saipan","created_at"=> $now,],
        ["name"=>"Samoa ","zone_value"=>"Pacific/Samoa","created_at"=> $now,],
        ["name"=>"Tahiti,PF","zone_value"=>"Pacific/Tahiti","created_at"=> $now,],
        ["name"=>"Tarawa,KI","zone_value"=>"Pacific/Tarawa","created_at"=> $now,],
        ["name"=>"Tonga,TO","zone_value"=>"Pacific/Tongatapu","created_at"=> $now,],
        ["name"=>"Micronesia,FM","zone_value"=>"Pacific/Truk","created_at"=> $now,],
        ["name"=>"Wake,UM","zone_value"=>"Pacific/Wake","created_at"=> $now,],
        ["name"=>"Wallis & Futuna,WF","zone_value"=>"Pacific/Wallis","created_at"=> $now,],
        ["name"=>"Micronesia ","zone_value"=>"Pacific/Yap","created_at"=> $now,],
        ["name"=>"Poland,PL","zone_value"=>"Poland","created_at"=> $now,],
        ["name"=>"Portugal,PT","zone_value"=>"Portugal","created_at"=> $now,],
        ["name"=>"PRC,CA","zone_value"=>"PRC","created_at"=> $now,],
        ["name"=>"PST8PDT","zone_value"=>"PST8PDT","created_at"=> $now,],
        ["name"=>"ROC","zone_value"=>"ROC","created_at"=> $now,],
        ["name"=>"Asia/Seoul","zone_value"=>"ROK","created_at"=> $now,],
        ["name"=>"Singapore","zone_value"=>"Singapore","created_at"=> $now,],
        ["name"=>"Turkey,TR","zone_value"=>"Turkey","created_at"=> $now,],
        ["name"=>"Coordinated Universal Time,UTC","zone_value"=>"UCT","created_at"=> $now,],
        ["name"=>"Universal","zone_value"=>"Universal","created_at"=> $now,],
        ["name"=>"Juneau,US","zone_value"=>"US/Alaska","created_at"=> $now,],
        ["name"=>"Hawaii Aleutian,HST","zone_value"=>"US/Aleutian","created_at"=> $now,],
        ["name"=>"Phoenix,USA","zone_value"=>"US/Arizona","created_at"=> $now,],
        ["name"=>"Central Time ,CT","zone_value"=>"US/Central","created_at"=> $now,],
        ["name"=>" East Central Indiana","zone_value"=>"US/East-Indiana","created_at"=> $now,],
        ["name"=>"Eastern Standard Time,EST","zone_value"=>"US/Eastern","created_at"=> $now,],
        ["name"=>"Hawaii,USA","zone_value"=>"US/Hawaii","created_at"=> $now,],
        ["name"=>" Starke,USA","zone_value"=>"US/Indiana-Starke","created_at"=> $now,],
        ["name"=>"Lansing,USA","zone_value"=>"US/Michigan","created_at"=> $now,],
        ["name"=>"Mountain ,USA","zone_value"=>"US/Mountain","created_at"=> $now,],
        ["name"=>"Pacific ,USA","zone_value"=>"US/Pacific","created_at"=> $now,],
        ["name"=>"Samoa ,USA","zone_value"=>"US/Samoa","created_at"=> $now,],
        ["name"=>"Coordinated Universal Time,UTC","zone_value"=>"UTC","created_at"=> $now,],
        ["name"=>"Europe/Moscow","zone_value"=>"W-SU","created_at"=> $now,],
        ["name"=>"Western European Time,WET","zone_value"=>"WET","created_at"=> $now,],
        ["name"=>"Zulu","zone_value"=>"Zulu","created_at"=> $now,],
        ];

        CompaniesTimezone::insert($industries);
    }
}
