<?php

namespace Database\Seeders\Seedersportal;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('modules')->truncate();

        $modules = array(
            array(
                    'id' => '49',
                    'title' => 'My Dashboard',
                    'description' => NULL,
                    'url' => 'dashboard',
                    'icon' => 'my_dashboard_icon',
                    'parent_module_id' => '0',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '1',
                    'module_type' => 1
                ),
            array(
                    'id' => '73',
                    'title' => 'My Assignments',
                    'description' => NULL,
                    'url' => 'my-assignments',
                    'icon' => 'my_Assignments_icon',
                    'parent_module_id' => '0',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '2',
                    'module_type' => 1
                ),
            array(
                    'id' => '15',
                    'title' => 'My Courses',
                    'description' => 'User assigned courses only',
                    'url' => 'mycourses/list',
                    'icon' => 'MyCourses',
                    'parent_module_id' => '73',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '1',
                    'module_type' => 1
                ),
            array(
                    'id' => '74',
                    'title' => 'My Tasks',
                    'description' => 'User assigned task only',
                    'url' => 'mytask/list',
                    'icon' => 'myTasks',
                    'parent_module_id' => '73',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '2',
                    'module_type' => 1
                ),
            array(
                    'id' => '76',
                    'title' => 'My Snapshots',
                    'description' => 'User Snapshots only',
                    'url' => 'mysnapshots',
                    'icon' => 'mySnapshots',
                    'parent_module_id' => '73',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '3',
                    'module_type' => 1
                ),
            array(
                    'id' => '75',
                    'title' => 'My Timesheet',
                    'description' => 'User Timesheet only',
                    'url' => 'mytimesheet',
                    'icon' => 'myTimesheet',
                    'parent_module_id' => '73',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '4',
                    'module_type' => 1
                ),
            array(
                    'id' => '19',
                    'title' => 'Trainings',
                    'description' => 'courses and articles',
                    'url' => '',
                    'icon' => 'Training',
                    'parent_module_id' => '0',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '3',
                    'module_type' => 1
                ),
            array(
                    'id' => '12',
                    'title' => 'Courses',
                    'description' => 'courses list',
                    'url' => 'courses/list',
                    'icon' => 'Courses',
                    'parent_module_id' => '19',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '1',
                    'module_type' => 1
                ),
            array(
                    'id' => '18',
                    'title' => 'Quizzes',
                    'description' => 'f',
                    'url' => 'quiz/list',
                    'icon' => 'Quizzes',
                    'parent_module_id' => '19',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '2',
                    'module_type' => 1
                ),
            array(
                    'id' => '14',
                    'title' => 'Articles',
                    'description' => 'Articles list here',
                    'url' => 'articles/list',
                    'icon' => 'Articles',
                    'parent_module_id' => '19',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '3',
                    'module_type' => 1
                ),
            array(
                    'id' => '13',
                    'title' => 'Projects & Tasks',
                    'description' => NULL,
                    'url' => '',
                    'icon' => 'Projects-and-Task',
                    'parent_module_id' => '0',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '4',
                    'module_type' => 1
                ),
            array(
                    'id' => '1',
                    'title' => 'Projects',
                    'description' => 'Projects',
                    'url' => 'projects/list',
                    'icon' => 'projects',
                    'parent_module_id' => '13',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '1',
                    'module_type' => 1
                ),
            array(
                    'id' => '2',
                    'title' => 'Tasks',
                    'description' => 'Activities',
                    'url' => 'activities',
                    'icon' => 'Tasks',
                    'parent_module_id' => '13',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '2',
                    'module_type' => 1
                ),
            array(
                    'id' => '5',
                    'title' => 'Clients',
                    'description' => 'Clients',
                    'url' => 'clients',
                    'icon' => 'Clients',
                    'parent_module_id' => '13',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '3',
                    'module_type' => 1
                ),
            array(
                    'id' => '50',
                    'title' => 'Monitoring',
                    'description' => NULL,
                    'url' => 'NULL',
                    'icon' => 'new_montiring_icon',
                    'parent_module_id' => '0',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '5',
                    'module_type' => 1
                ),
            array(
                    'id' => '48',
                    'title' => 'Live Dashboard',
                    'description' => NULL,
                    'url' => 'live-dashboard',
                    'icon' => 'Live_Dashboard',
                    'parent_module_id' => '50',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '1',
                    'module_type' => 1
                ),
            array(
                    'id' => '52',
                    'title' => 'Team Dashboard',
                    'description' => NULL,
                    'url' => 'team-dashboard',
                    'icon' => 'My_Dashboard',
                    'parent_module_id' => '50',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '2',
                    'module_type' => 1
                ),
            array(
                    'id' => '47',
                    'title' => 'Timesheet',
                    'description' => 'NULL',
                    'url' => 'split_time',
                    'icon' => 'split_time',
                    'parent_module_id' => '50',
                    'deleted_at' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'module_order' => '3',
                    'module_type' => 1
                ),
            array(
                    'id' => '9',
                    'title' => 'Snapshots',
                    'description' => 'Snapshots',
                    'url' => 'snapshots',
                    'icon' => 'Snapshots',
                    'parent_module_id' => '50',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '4',
                    'module_type' => 1
                ),
            array(
                    'id' => '51',
                    'title' => 'Web & App Tracking',
                    'description' => NULL,
                    'url' => 'web_app_tracking',
                    'icon' => 'Web_App_Tracking',
                    'parent_module_id' => '50',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '5',
                    'module_type' => 1
                ),
            array(
                    'id' => '22',
                    'title' => 'Resource Management',
                    'description' => '',
                    'url' => '',
                    'icon' => 'Employee_management',
                    'parent_module_id' => '0',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '6',
                    'module_type' => 1
                ),
            array(
                    'id' => '25',
                    'title' => 'Employees',
                    'description' => NULL,
                    'url' => 'hiring/list',
                    'icon' => 'Hiring',
                    'parent_module_id' => '22',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '1',
                    'module_type' => 1
                ),
            array(
                    'id' => '26',
                    'title' => 'Departments',
                    'description' => NULL,
                    'url' => 'departments',
                    'icon' => 'departments',
                    'parent_module_id' => '22',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '2',
                    'module_type' => 1
                ),
            array(
                    'id' => '31',
                    'title' => 'Teams',
                    'description' => 'Teams',
                    'url' => 'groups',
                    'icon' => 'groups',
                    'parent_module_id' => '22',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '3',
                    'module_type' => 1
                ),
            array(
                    'id' => '77',
                    'title' => 'Scheduling Management',
                    'description' => 'Scheduling Management',
                    'url' => '',
                    'icon' => 'Scheduling_Management',
                    'parent_module_id' => '0',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '7',
                    'module_type' => 1
                ),
            array(
                    'id' => '27',
                    'title' => 'Shift Scheduling',
                    'description' => NULL,
                    'url' => 'shifts',
                    'icon' => 'Shift_Schedule',
                    'parent_module_id' => '77',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '1',
                    'module_type' => 1
                ),
            array(
                    'id' => '28',
                    'title' => 'Break Scheduling',
                    'description' => 'Break Scheduling',
                    'url' => 'breaks',
                    'icon' => 'Break_Schedule',
                    'parent_module_id' => '77',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '2',
                    'module_type' => 1
                ),
            array(
                    'id' => '78',
                    'title' => 'Reports',
                    'description' => NULL,
                    'url' => 'module-reports',
                    'icon' => 'Reports',
                    'parent_module_id' => '0',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '8',
                    'module_type' => 1
                ),
            array(
                    'id' => '71',
                    'title' => 'Course Time Report',
                    'description' => 'Training Reports',
                    'url' => 'module-reports/course-time-reports',
                    'icon' => 'course_time_report_icon',
                    'parent_module_id' => '78',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '1',
                    'module_type' => 1
                ),
            array(
                    'id' => '72',
                    'title' => 'Course Performance Report',
                    'description' => 'Training Reports',
                    'url' => 'module-reports/course-performance-reports',
                    'icon' => 'course_performance_report_icon',
                    'parent_module_id' => '78',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '2',
                    'module_type' => 1
                ),
            array(
                    'id' => '62',
                    'title' => 'Project Time Report',
                    'description' => NULL,
                    'url' => 'module-reports/projects-time-report',
                    'icon' => 'project_time_report_icon',
                    'parent_module_id' => '78',
                    'deleted_at' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'module_order' => '3',
                    'module_type' => 1
                ),
            array(
                    'id' => '57',
                    'title' => 'User Time Report',
                    'description' => NULL,
                    'url' => 'module-reports/user-time-report',
                    'icon' => 'user_time_report_icon',
                    'parent_module_id' => '78',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '4',
                    'module_type' => 1
                ),
            array(
                'id' => '58',
                'title' => 'Idle & Manual Time Report',
                'description' => NULL,
                'url' => 'module-reports/idle-manual-time-report',
                'icon' => 'idle_manual_time_report_icon',
                'parent_module_id' => '78',
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => NULL,
                'module_order' => '5',
                'module_type' => 1
            ),
            array(
                'id' => '59',
                'title' => 'Team Work Report',
                'description' => NULL,
                'url' => 'module-reports/team-work-report',
                'icon' => 'team_work_report_icon',
                'parent_module_id' => '78',
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => NULL,
                'module_order' => '6',
                'module_type' => 1
            ),
            array(
                    'id' => '61',
                    'title' => 'Configurations',
                    'description' => 'Configurations',
                    'url' => NULL,
                    'icon' => 'Configurations',
                    'parent_module_id' => '0',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '9',
                    'module_type' => 1
                ),
            array(
                    'id' => '44',
                    'title' => 'Company Settings',
                    'description' => 'Company',
                    'url' => 'company/edit',
                    'icon' => 'Company',
                    'parent_module_id' => '61',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '1',
                    'module_type' => 1
                ),
            array(
                    'id' => '63',
                    'title' => 'General Settings',
                    'description' => 'General Settings',
                    'url' => '-',
                    'icon' => 'Company',
                    'parent_module_id' => '44',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '1',
                    'module_type' => 2
                ),
            array(
                    'id' => '65',
                    'title' => 'Organization',
                    'description' => 'Organization',
                    'url' => '-',
                    'icon' => 'Company',
                    'parent_module_id' => '63',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '1',
                    'module_type' => 2
                ),
            array(
                    'id' => '66',
                    'title' => 'Display Settings',
                    'description' => 'Display Settings',
                    'url' => '-',
                    'icon' => 'Company',
                    'parent_module_id' => '63',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '1',
                    'module_type' => 2
                ),
            array(
                    'id' => '64',
                    'title' => 'Monitoring',
                    'description' => 'Monitoring',
                    'url' => '-',
                    'icon' => 'Company',
                    'parent_module_id' => '44',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '2',
                    'module_type' => 2
                ),
            array(
                    'id' => '67',
                    'title' => 'Time Tracking',
                    'description' => 'Monitoring',
                    'url' => '-',
                    'icon' => 'Company',
                    'parent_module_id' => '64',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '1',
                    'module_type' => 2
                ),
            array(
                    'id' => '68',
                    'title' => 'Others',
                    'description' => 'Monitoring',
                    'url' => '-',
                    'icon' => 'Company',
                    'parent_module_id' => '64',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '2',
                    'module_type' => 2
                ),
            // array(
            //         'id' => '69',
            //         'title' => 'Idle Time',
            //         'description' => 'Monitoring',
            //         'url' => '-',
            //         'icon' => 'Company',
            //         'parent_module_id' => '64',
            //         'deleted_at' => NULL,
            //         'created_at' => date('Y-m-d H:i:s'),
            //         'updated_at' => NULL,
            //         'module_order' => '3',
            //         'module_type' => 2
            //     ),
            array(
                    'id' => '70',
                    'title' => 'Off Days Calendar',
                    'description' => 'Monitoring',
                    'url' => '-',
                    'icon' => 'Company',
                    'parent_module_id' => '63',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '4',
                    'module_type' => 2
                ),
            array(
                    'id' => '37',
                    'title' => 'Profile and Permissions',
                    'description' => 'Profile and Permissions',
                    'url' => 'profiles',
                    'icon' => 'profile_permissions',
                    'parent_module_id' => '61',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '2',
                    'module_type' => 1
                ),
            array(
                    'id' => '11',
                    'title' => 'Download client',
                    'description' => 'Download Setup',
                    'url' => 'setup',
                    'icon' => 'Download',
                    'parent_module_id' => '0',
                    'deleted_at' => NULL,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => NULL,
                    'module_order' => '11',
                    'module_type' => 1
                ),
        );
        DB::table('modules')->insert($modules);
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
